Develop
buggisart/Sprint_4 pull request #1
Opened 2023-03-26 11:53 UTC by buggisart

2023-03-26 17:41 UTC, pavel-ulan requested changes
Неплохо, только начнем с того, что папку .idea не коммитят в репозиторий. Я вижу, что ты добавил ее в gitignore но видимо перед этим успел добавить в коммит (кстати, еще стоит добавить *.iml).
Я оставил комменты, глянь, может быть полезно

2023-03-26 17:41 UTC, pavel-ulan commented on src/main/java/PageObject/MainPage.java
> +            By.xpath(".//div[@class = 'Header_Nav__AGCXC']/button[@class = 'Button_Button__ra12g']");
**можно лучше**
не то, что бы это совсем неправильно, но все же делать локаторы константами не самое популярное решение. все же правильнее было бы оставить это просто приватными полями

2023-03-26 17:41 UTC, pavel-ulan commented on src/main/java/PageObject/OrderPage/PersonalData.java
> +            By.xpath(".//input[@placeholder='* Имя']");
**надо исправить**
А вот тут уже стоило бы следовать намеченному плану (раз уж использовал константы). тут твоя ошибка заключается в том, что ты используешь константу, но имя написано в lowerCamelCase (а константы именуются в UPPER_CASE)

2023-03-26 17:41 UTC, pavel-ulan commented on src/main/java/PageObject/OrderPage/RentData.java
> +            By.xpath(".//div[@class='Order_Buttons__1xGrp']/button[text() = 'Заказать']");
**просто заметка**
странно выглядит, что у тебя все локаторы приватные, а этот дефолтный. так было задумано или просто упустил?

2023-03-26 17:41 UTC, pavel-ulan commented on src/test/java/CreateOrderTest.java
> +    // во всплывающем окне должна быть фраза "Заказ оформлен"
Да, все верно, так и должно быть.

2023-03-26 17:41 UTC, pavel-ulan commented on src/test/java/CreateOrderTest.java
> +        RentData rentData = new RentData(driver);
**можно лучше**
не очень правильно создавать и инициализировать объекты PO внутри тестового метода. почему? - ты создаешь объекты внутри теста, внутри каждого теста, тем самым засоряешь память. это не критично, но все же так делать не следует.
как правило PO модели в тестовые классы инжектают (как вариант можно создать и инициализировать сразу в полях класса. тогда как минимум объекты PO будут созданы однажды)

2023-03-26 17:41 UTC, pavel-ulan commented on src/test/java/CreateOrderTest.java
> +        но я решил оставить ожидание, как в настоящем тесте, проверяющим полный позитивный флоу, где мы все-таки ждем это окно */
баг заложен в хром браузер, в фаерфоксе все проходит хорошо. именно по этой причине в задании и просят тестить на разных браузерах (и в целом это хорошая практика тестировать на нескольких браузерах)

2023-03-26 17:55 UTC, buggisart commented on src/main/java/PageObject/MainPage.java
> +            By.xpath(".//div[@class = 'Header_Nav__AGCXC']/button[@class = 'Button_Button__ra12g']");
Окей, учту на будущее,  локаторы делали константами  на веминаре по силенеуму

2023-03-26 19:05 UTC, buggisart commented on src/test/java/CreateOrderTest.java
> +        RentData rentData = new RentData(driver);
поправил, вынес в метод с аннотацией @Before

2023-03-26 19:06 UTC, buggisart commented on src/test/java/CreateOrderTest.java
> +    // во всплывающем окне должна быть фраза "Заказ оформлен"
хорошо, спасибо)

2023-03-26 19:06 UTC, buggisart commented on src/main/java/PageObject/OrderPage/RentData.java
> +            By.xpath(".//div[@class='Order_Buttons__1xGrp']/button[text() = 'Заказать']");
поправил

2023-03-26 19:06 UTC, buggisart commented on src/main/java/PageObject/OrderPage/PersonalData.java
> +            By.xpath(".//input[@placeholder='* Имя']");
исправил

2023-03-26 20:25 UTC, buggisart commented on src/test/java/CreateOrderTest.java
> +        но я решил оставить ожидание, как в настоящем тесте, проверяющим полный позитивный флоу, где мы все-таки ждем это окно */
Окей

2023-03-28 12:11 UTC, pavel-ulan commented on src/main/java/PageObject/MainPage.java
> +            By.xpath(".//div[@class = 'Header_Nav__AGCXC']/button[@class = 'Button_Button__ra12g']");
ну, я и говорю, не то что бы это неправильно, но все же менее популярно (возможно это было чем-то обосновано в примере на котором вам показывали)

2023-03-28 12:13 UTC, pavel-ulan approved these changes
👍

2023-03-28 12:39 UTC, merged